name: Build and Deploy WebGL and Documentation

concurrency: production-${{ github.ref }}

on:
  push:
    branches:
      - 'main'

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build-treachery-app:
    name: Build Treachery WebGL App
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setvars
      - uses: ./.github/actions/git-lfs-cache
      - uses: ./.github/actions/unity-library-cache
        with:
          target_platform: WebGL

      # Build the game deployment at build
      - uses: game-ci/unity-builder@v2.0.4
        with:
          unityVersion: ${{ env.UNITY_VERSION }}
          targetPlatform: WebGL
          buildMethod: ScriptBatch.OfficialBuild_WebGL

      # save build to temp_build_treachery_webgl
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: temp_build_treachery_webgl
          path: Builds/${{ env.PROJECT_NAME }}

  # Build the documentation
  build-docs:
    name: DocFX build for website
    runs-on: windows-latest # Required by DocFX
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setvars
      - uses: ./.github/actions/git-lfs-cache

      - name: Install DocFX
        run: choco install -y docfx

      - name: Build Website
        run: .\Documentation\build.cmd

      # Upload build to temp_build_docs_webgl
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: temp_build_docs_webgl
          path: _site

  # Deploy the built branches
  combine-and-deploy-app:
    name: Combine built apps and deploy to gh-pages
    runs-on: ubuntu-latest
    needs: [build-treachery-app, build-docs]
    steps:
      # Download previous builds
      - name: Download WebGL Build
        uses: actions/download-artifact@v3
        with:
          name: temp_build_treachery_webgl
          path: _site

      - name: Download Docs Build
        uses: actions/download-artifact@v3
        with:
          name: temp_build_docs_webgl
          path: _site/docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          force_orphan: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          publish_branch: gh-pages

  # Cleanup the build artifacts
  cleanup-build-artifacts:
    name: Cleanup the build artifacts after deploying site.
    runs-on: ubuntu-latest
    if: always()
    needs: [build-treachery-app, build-docs, combine-and-deploy-app]

    steps:
      - name: Cleanup temp build artifacts
        uses: joutvhu/delete-artifact@v1
        with:
          name: |
            temp_build_treachery_webgl
            temp_build_docs_webgl
